name: Sync Upstream
# Uses https://github.com/marketplace/actions/sync-and-merge-upstream-repository-with-your-current-repository

on:
  schedule:
    # 11:30am UTC
    - cron: "30 11 * * *"
  # Allows manual workflow run (must in default branch to work)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: GitHub Sync to Upstream Repository
        uses: dabreadman/sync-upstream-repo@v1.3.0
        with:
          upstream_repo: "https://github.com/Recycleye/labelbox-python.git"
          upstream_branch: "develop"
          downstream_branch: "develop"
          token: ${{ secrets.GITHUB_TOKEN }}
